custom_order = [
    "Flerbostadshus",
    "Smahus",
    "LOM Flerbostadshus",
    "LOM Smahus",
    "RAPS 1 3",
    "RAPS 4",
    "RAPS 5",
    "RAPS 6",
    "RAPS 7",
    "RAPS 8",
    "RAPS 9",
    "RAPS 10",
    "RAPS 11",
    "RAPS 12",
    "RAPS 13",
    "RAPS 14",
    "RAPS 15",
    "RAPS 16",
    "RAPS 17",
    "RAPS 18",
    "RAPS 19",
    "RAPS 20",
    "RAPS 21",
    "RAPS 22",
    "RAPS 23",
    "RAPS 24",
    "RAPS 27",
    "RAPS 7777",
    "RAPS 8888",
    "PB",
    "LL",
    "TT DEP",
    "TT DEST",
    "TT RESTSTOP",
]

category_groups = {
    "total": custom_order,
    "bostader": ["Flerbostadshus", "Smahus", "LOM Flerbostadshus", "LOM Smahus"],
    "industri_och_bygg": [],
    "offentlig_och_privat_sektor": [],
    "transport": ["PB", "LL", "TT DEP", "TT DEST", "TT RESTSTOP"],
    "jordbruk_skogsbruk": [],
}
